name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout-composer-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

  phpcbf-commit-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache multiple paths
      uses: actions/cache@v3
      with:
        path: |
          ~/cache
          !~/cache/exclude
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install PHP CodeSniffer
      run: |
        composer require --dev dealerdirect/phpcodesniffer-composer-installer
        composer require --dev drupal/coder
    
    - name: Fixing coding standards - phpcbf
      id: run-phpcbf
      run: sh ./.github/workflows/script.sh
        
    - name: Commit Fixes
      if: ${{ steps.run-phpcbf.outputs.FIXED }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Fixing phpcbf changes

    - name: Check coding standards - phpcs 
      run: vendor/bin/phpcs

  Greeting:
    runs-on: ubuntu-latest
    steps: 
    - name: Greeting
      run: echo Successfully Done!!    
          