name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
 
    - name: Install PHP CodeSniffer
      run: |
        composer require --dev dealerdirect/phpcodesniffer-composer-installer
    
    - name: Cache CS packages
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-       
  
    - name: Fixing coding standards
      id: run-phpcbf
      run: 
        vendor/bin/phpcbf
        retVal=$?
        if [ $retVal -eq 1 ]; then
            echo "Some Files Fixed"
            echo '::set-output name=FIXED::true'
            exit 0
        fi
        exit $retVal

    - name: Commit Fixes
      if: ${{ steps.run-phpcbf.outputs.FIXED }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply php-cs-fixer changes

    - name: Check coding standards
      run: vendor/bin/phpcs            
         

     
      
